# Site settings
title: DacTales
logo: logo.png
print_title_with_logo: false
email: contact@dactales.com
url: https://github.com/dactales
description: ""
keywords: "blockchain graphene development full-stack"
skills: "We know about decentralized business"

about_left: "We are a team of experts that has been building applications on Blockchains since 2014."
about_right: "Blockchain as a technology dates back to 2009. We dived in, first as fans, then professionally. We established our company with a strong international focus. To date, our team involves Blockchain as well as Business and Marketing experts with extensive international experience, network and academic background."

meta_author: "DacTales B.V."

expertise:
  slogan: "Customer first, process second, technology third"
  left:
  - "Blockchain A to Z"
  right:
  - "Modeling, Design & Tokenomics"
  - "Decentralization & Centralization"
  - "Development"
  - "Continous Integration and Deployment"
  - "Marketing and Brand Consultancy"
  - "Boardroom Processes & Establishing Business Goals"


# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 69AFF7
  primary-rgb: 105,175,247
  secondary: 698BF7
  secondary-dark: 6A69F7

# Footer settings
footer:
  copyright: DacTales B.V.
  location: Company
  social: Around the Web
  credits:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/dactales

# Postal address (add as many lines as necessary)
address:
  - line: DacTales B.V.  
  - line: Pelmolenlaan 2
  - line: 3447GW Woerden, Netherlands
  - line: "KvK Number: 77934849"

# Credits content
credits: ''

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
