# Site settings
title: DacTales
email: contact@dactales.com
url: https://github.com/dactales
description: ""
keywords: "blockchain graphene development full-stack"
skills: "We know about decentralized business"
meta_author: 

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 69AFF7
  primary-rgb: 105,175,247
  secondary: 698BF7
  secondary-dark: 6A69F7

# Footer settings
footer:
  copyright: DacTales B.V.
  location: The Netherlands
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#   - title: twitter
#     url: http://twitter.com/dactales
#   - title: facebook
#     url:
#   - title: stack-overflow
#     url: http://stackoverflow.com/questions/tagged/jekyll
#   - title: bitbucket
#     url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/dactales

# Postal address (add as many lines as necessary)
address:
  - line: Pelmolenlaan 2
  - line: 3447GW Woerden

# Credits content
credits: ''

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
